<script>
    /** @type {import('./$types').PageData} */
    export let data;
    
    const { stakeholders } = data;
</script>

<div class="recognition-container">
    <h2>🏆 Stakeholder Recognition</h2>
    <p class="subtitle">We highlight the Ministries, Parastatals, and organizations that have formally acknowledged and engaged with policy briefs generated by youth solutions.</p>

    {#if stakeholders && stakeholders.length > 0}
        <div class="stakeholders-grid">
            {#each stakeholders as stakeholder (stakeholder.name)}
                <div class="stakeholder-card">
                    <span class="logo-placeholder">🏛️</span>
                    <h3>{stakeholder.name}</h3>
                    <p class="acknowledgment-count">Acknowledged **{stakeholder.briefs.length}** Policy Brief(s)</p>
                    
                    <ul class="brief-list">
                        {#each stakeholder.briefs as briefTitle}
                            <li><span class="bullet">✅</span> {briefTitle}</li>
                        {/each}
                    </ul>
                </div>
            {/each}
        </div>
    {:else}
        <div class="empty-state">
            <h3>Awaiting First Acknowledgment</h3>
            <p>Our policy briefs have been delivered. We eagerly await formal acknowledgment from government stakeholders!</p>
        </div>
    {/if}
</div>

<style>
    .recognition-container {
        padding: 20px 0;
    }
    
    h2 {
        font-size: 2.2em;
        font-weight: 700;
        margin-bottom: 5px;
        color: var(--color-text-dark);
        text-align: center;
    }

    .subtitle {
        text-align: center;
        color: var(--color-text-light);
        margin-bottom: 40px;
        font-size: 1.1em;
    }

    .stakeholders-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
        gap: 30px;
    }

    .stakeholder-card {
        background-color: var(--color-white);
        border: 1px solid var(--color-border-light);
        border-top: 5px solid var(--color-secondary-accent);
        padding: 25px;
        border-radius: 8px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    }
    
    .logo-placeholder {
        display: block;
        font-size: 3em;
        margin-bottom: 10px;
    }

    .stakeholder-card h3 {
        color: var(--color-text-dark);
        font-size: 1.6em;
        margin-bottom: 10px;
    }

    .acknowledgment-count {
        font-weight: 600;
        color: var(--color-primary-accent);
        margin-bottom: 15px;
    }
    
    .brief-list {
        list-style: none;
        padding: 0;
        margin-top: 10px;
        border-top: 1px dashed var(--color-border-light);
        padding-top: 15px;
    }

    .brief-list li {
        color: var(--color-text-light);
        margin-bottom: 5px;
        font-size: 0.9em;
    }
    
    .bullet {
        color: var(--color-primary-accent);
        margin-right: 5px;
    }

    .empty-state {
        text-align: center;
        padding: 60px;
        background-color: var(--color-white);
        border: 1px dashed var(--color-border-light);
        border-radius: 8px;
        margin: 40px auto;
        max-width: 700px;
    }
    
    .empty-state h3 {
        color: var(--color-secondary-accent);
        margin-bottom: 10px;
    }
</style>